### ISSUE TITLE
issues in transmil.py

### ISSUE THREAD

**Issue by wangjie6866** [ChongQingNoSubway/PDL#1]
I have met the issue  "AttributeError: 'Lookahead' object has no attribute '_optimizer_step_pre_hooks"  when I run the tansmil.py, do you kown the reason? Thanks.

**Comment by ChongQingNoSubway** [comment]
It usually happened due to the pytorch version. 
You can directly use the timm lib to call the lookahead optimizer. 
Please refer to : https://github.com/huggingface/pytorch-image-models/blob/6e6f3686a7e06bcba37bbd3b7c755f04a516a1e7/timm/optim/lookahead.py#L15
